/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin processor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"
#include "Chord.h"

//==============================================================================
TestAudioProcessor::TestAudioProcessor()
{
}

TestAudioProcessor::~TestAudioProcessor()
{
}

//==============================================================================
const String TestAudioProcessor::getName() const
{
    return JucePlugin_Name;
}

int TestAudioProcessor::getNumParameters()
{
    return 0;
}

float TestAudioProcessor::getParameter (int index)
{
    return 0.0f;
}

void TestAudioProcessor::setParameter (int index, float newValue)
{
}

const String TestAudioProcessor::getParameterName (int index)
{
    return String();
}

const String TestAudioProcessor::getParameterText (int index)
{
    return String();
}

const String TestAudioProcessor::getInputChannelName (int channelIndex) const
{
    return String (channelIndex + 1);
}

const String TestAudioProcessor::getOutputChannelName (int channelIndex) const
{
    return String (channelIndex + 1);
}

bool TestAudioProcessor::isInputChannelStereoPair (int index) const
{
    return true;
}

bool TestAudioProcessor::isOutputChannelStereoPair (int index) const
{
    return true;
}

bool TestAudioProcessor::acceptsMidi() const
{
   #if JucePlugin_WantsMidiInput
    return true;
   #else
    return false;
   #endif
}

bool TestAudioProcessor::producesMidi() const
{
   #if JucePlugin_ProducesMidiOutput
    return true;
   #else
    return false;
   #endif
}

bool TestAudioProcessor::silenceInProducesSilenceOut() const
{
    return false;
}

double TestAudioProcessor::getTailLengthSeconds() const
{
    return 0.0;
}

int TestAudioProcessor::getNumPrograms()
{
    return 1;   // NB: some hosts don't cope very well if you tell them there are 0 programs,
                // so this should be at least 1, even if you're not really implementing programs.
}

int TestAudioProcessor::getCurrentProgram()
{
    return 0;
}

void TestAudioProcessor::setCurrentProgram (int index)
{
}

const String TestAudioProcessor::getProgramName (int index)
{
    return String();
}

void TestAudioProcessor::changeProgramName (int index, const String& newName)
{
}

//==============================================================================
void TestAudioProcessor::prepareToPlay (double sampleRate, int samplesPerBlock)
{
    // Use this method as the place to do any pre-playback
    // initialisation that you need..
}

void TestAudioProcessor::releaseResources()
{
    // When playback stops, you can use this as an opportunity to free up any
    // spare memory, etc.
}

void TestAudioProcessor::GetChords()
{
    Chord::ReadChords();

}

void TestAudioProcessor::processBlock (AudioSampleBuffer& buffer, MidiBuffer& midiMessages)
{
    // In case we have more outputs than inputs, this code clears any output
    // channels that didn't contain input data, (because these aren't
    // guaranteed to be empty - they may contain garbage).
    // I've added this to avoid people getting screaming feedback
    // when they first compile the plugin, but obviously you don't need to
    // this code if your algorithm already fills all the output channels.
    for (int i = getNumInputChannels(); i < getNumOutputChannels(); ++i)
        buffer.clear (i, 0, buffer.getNumSamples());

    MidiBuffer processedMidi;
    int time;
    MidiMessage m;
    
    /*std::cout << "mode slider: ";
    std::cout << modeSlider;
    std::cout << "\n";
    
    std::cout << "key slider: ";
    std::cout << keySlider;
    std::cout << "\n";

    std::cout << "chord button: ";
    std::cout << chordMode;
    std::cout << "\n";
*/
    String t4;
    int chordArrayLength = 6;
    
    for(MidiBuffer::Iterator i (midiMessages); i.getNextEvent(m, time);)
    {
        if(m.isNoteOn()) {
            int noteNumber = m.getNoteNumber() + (int) keySlider;

            if(chordMode) {
                int chordIntervals[chordArrayLength];

                chordStructure.ReadChords();

                int * intervalsPointer = chordStructure.GetChord(chordIntervals, chordChooser);

                for(int i = 0;i<chordArrayLength;i++) {
                    if(intervalsPointer[i] == 0)
                        break;

                    int interval = m.getNoteNumber() + intervalsPointer[i];
                    MidiMessage n = MidiMessage::noteOn(m.getChannel(), interval, m.getFloatVelocity());
                    processedMidi.addEvent(n, time);
                }
            }
            else {
                noteNumber = (modeSlider == 0) ?
                        noteNumber + chordStructure.GetRandomMinorNote() :
                        noteNumber + chordStructure.GetRandomMajorNote();

                m = MidiMessage::noteOn(m.getChannel(), noteNumber, m.getFloatVelocity());
                cachedNote = m;

                processedMidi.addEvent(m, time);
            }
        }
        
        else if(m.isNoteOff())
        {
            MidiMessage n = MidiMessage::allNotesOff(m.getChannel());
            processedMidi.addEvent(n, time);
        }
    }
    midiMessages.swapWith(processedMidi);
}

int TestAudioProcessor::getInterval(int noteNumber, const int *chordIntervals, int i) const {
    return noteNumber + chordIntervals[i];
}

//==============================================================================
bool TestAudioProcessor::hasEditor() const
{
    return true; // (change this to false if you choose to not supply an editor)
}

AudioProcessorEditor* TestAudioProcessor::createEditor()
{
    return new TestAudioProcessorEditor (*this);
}

//==============================================================================
void TestAudioProcessor::getStateInformation (MemoryBlock& destData)
{
    // You should use this method to store your parameters in the memory block.
    // You could do that either as raw data, or use the XML or ValueTree classes
    // as intermediaries to make it easy to save and load complex data.
}

void TestAudioProcessor::setStateInformation (const void* data, int sizeInBytes)
{
    // You should use this method to restore your parameters from this memory block,
    // whose contents will have been created by the getStateInformation() call.
}

//==============================================================================
// This creates new instances of the plugin..
AudioProcessor* JUCE_CALLTYPE createPluginFilter()
{
    return new TestAudioProcessor();
}
